services:
  postgres:
    image: postgres:15
    container_name: brickbrain-postgres
    environment:
      POSTGRES_USER: brickbrain
      POSTGRES_PASSWORD: brickbrain_password
      POSTGRES_DB: brickbrain
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U brickbrain"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: