services:
  postgres:
    image: postgres:15
    container_name: brickbrain-postgres
    environment:
      POSTGRES_USER: brickbrain
      POSTGRES_PASSWORD: brickbrain_password
      POSTGRES_DB: brickbrain
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U brickbrain"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: continuumio/miniconda3:latest
    container_name: brickbrain-app
    working_dir: /app
    volumes:
      - .:/app
      - conda_envs:/opt/conda/envs
      # Add volumes for NL features
      - model_cache:/app/.cache
      - embeddings_data:/app/embeddings
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_NAME=brickbrain
      - DB_USER=brickbrain
      - DB_PASSWORD=brickbrain_password
      - DB_PORT=5432
      # Add NL environment variables
      - TRANSFORMERS_CACHE=/app/.cache/huggingface
      - SENTENCE_TRANSFORMERS_HOME=/app/.cache/sentence-transformers
      - LANGCHAIN_CACHE_DIR=/app/.cache/langchain
      - TOKENIZERS_PARALLELISM=false
    command: |
      bash -c "
        if ! conda env list | grep -q brickbrain-rec; then
          echo 'Creating conda environment...'
          conda env create -f environment.yml -n brickbrain-rec
        fi &&
        echo 'Installing additional NL dependencies...' &&
        conda run -n brickbrain-rec pip install --quiet \
          langchain==0.1.16 \
          langchain-community==0.0.34 \
          sentence-transformers==2.6.1 \
          faiss-cpu==1.8.0 \
          chromadb==0.4.24 \
          nltk==3.8.1 &&
        echo 'Starting API with NL features...' &&
        conda run -n brickbrain-rec python src/scripts/recommendation_api.py
      "
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:8000/health\")' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Add resource limits for NL operations
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

volumes:
  postgres_data:
  conda_envs:
  model_cache:
  embeddings_data: