name: brickbrain-rec
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  # Core Python and data science packages from conda
  - python=3.10
  - pip>=23.0
  - pandas>=2.1.0
  - numpy>=1.25.0
  - scikit-learn>=1.3.0
  - matplotlib>=3.8.0
  - seaborn>=0.13.0
  - pytorch>=2.0.0
  - jupyter
  - ipykernel
  - pytest
  - pyyaml
  - requests>=2.31.0
  - pip:
    # Core Web Framework
    - fastapi==0.104.1
    - "uvicorn[standard]==0.24.0"
    
    # Database
    - sqlalchemy==2.0.23
    - psycopg2-binary==2.9.9
    - alembic==1.13.1
    
    # LangChain Stack
    - langsmith>=0.1.0,<0.2.0
    - langchain-core>=0.1.0
    - langchain>=0.1.4
    - langchain-openai==0.0.5
    - langchain-community>=0.0.14
    - langgraph==0.0.26
    
    # LLM Providers and Integration
    - transformers>=4.38.0
    - accelerate>=0.25.0
    - huggingface-hub>=0.23.0
    
    # Vector Stores and Embeddings
    - chromadb==0.4.22
    - sentence-transformers==2.6.0
    - tiktoken==0.5.2
    
    # Web Scraping and Data Processing
    - beautifulsoup4==4.12.2
    - scrapy==2.11.0
    
    # Data Validation
    - pydantic==2.5.2
    - pydantic-settings==2.1.0
    
    # Authentication & Security
    - "passlib[bcrypt]==1.7.4"
    - "python-jose[cryptography]==3.3.0"
    - python-multipart==0.0.6
    
    # Environment, Logging and utilities
    - python-dotenv==1.0.0
    - loguru==0.7.2
    
    # Testing
    - pytest-asyncio==0.21.1
    - httpx==0.25.2
    
    # Development Tools
    - black==23.12.1
    - flake8==6.1.0
    - isort==5.13.2
    - pre-commit==3.6.0
    
    # Documentation
    - mkdocs==1.5.3
    - mkdocs-material==9.4.8
    
    # Data Visualization
    - plotly==5.17.0
    - openpyxl==3.1.2
    
    # API and Background Processing
    - slowapi==0.1.9
    - celery==5.3.4
    - redis==5.0.1
    - gunicorn==21.2.0