name: brickbrain-rec
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  # Core Python and data science packages from conda
  - python=3.10
  - pip>=23.0
  - pandas>=2.1.0
  - numpy>=1.25.0
  - scikit-learn>=1.3.0
  - matplotlib>=3.8.0
  - seaborn>=0.13.0
  - pytorch>=2.0.0
  - jupyter
  - ipykernel
  - pytest
  - pyyaml
  - requests>=2.31.0
  - pip:
    # Core Web Framework
    - fastapi==0.116.0
    - "uvicorn[standard]==0.35.0"
    
    # Database
    - sqlalchemy==2.0.41
    - psycopg2-binary==2.9.10
    - alembic==1.16.2
    
    # LangChain Stack - Updated to v0.3.x (Breaking changes)
    - langsmith>=0.4.0,<0.5.0
    - langchain-core>=0.3.0
    - langchain>=0.3.26
    - langchain-openai==0.3.27
    - langchain-community>=0.3.27
    - langgraph==0.5.1
    
    # LLM Providers and Integration
    - transformers>=4.53.1
    - accelerate>=0.25.0
    - huggingface-hub>=0.23.0
    
    # Vector Stores and Embeddings
    - chromadb==1.0.15
    - sentence-transformers==5.0.0
    - tiktoken==0.9.0
    
    # Web Scraping and Data Processing
    - beautifulsoup4==4.13.4
    - scrapy==2.13.3
    
    # Data Validation
    - pydantic==2.11.7
    - pydantic-settings==2.10.1
    
    # Authentication & Security
    - "passlib[bcrypt]==1.7.4"
    - "python-jose[cryptography]==3.5.0"
    - python-multipart==0.0.20
    
    # Environment, Logging and utilities
    - python-dotenv==1.1.1
    - loguru==0.7.3
    
    # Testing
    - pytest-asyncio==1.0.0
    - httpx==0.28.1
    
    # Development Tools
    - black==25.1.0
    - flake8==7.3.0
    - isort==6.0.1
    - pre-commit==4.2.0
    
    # Documentation
    - mkdocs==1.6.1
    - mkdocs-material==9.6.15
    
    # Data Visualization
    - plotly==6.2.0
    - openpyxl==3.1.5
    
    # API and Background Processing
    - slowapi==0.1.9
    - celery==5.5.3
    - redis==6.2.0
    - gunicorn==23.0.0